function [] = run_sabcondv5(bland_id, target_id)
%% Declare variables and paths

% bland_id = '4774';
% target_id = '47A3';

hitran_path = '/home/imadk/Documents/MATLAB/CRISM/HITRAN/mars_hitran';
T_path = '/home/imadk/data/T';
results_path = './v5_results';


%% Batch processing of convolution.

crism_convolve_hitran_abscoef(bland_id, ...
    'ABSCOEF_DIR', hitran_path, 'mcd_ver', '6_1', 'max_nparallel', 16);

%%
crism_obs_ref = CRISMObservation(bland_id,'SENSOR_ID','L');
TRRIFdata_ref = CRISMdata(crism_obs_ref.info.basenameIF,'');
[out_bland2] = sabcondv5_pub(bland_id, ...
    'FFC_MODE', false, 'FFC_IF_COUNTER', 1, ...'LINES',100:200,...
    'WEIGHT_MODE', 1, 'cal_bias_cor', 0, ...
    ... % Transmission option
    't_mode', 5, 'obs_id_T', TRRIFdata_ref.basename, 'varargin_T', { ...
        'additional_suffix', 'mean_MCDv6_1_scena1_abscoef_2020_voigt_ctr_bin0', ...
        'dirpath', T_path ...
    },...
    'lambda_a', 0.02, 'opt_img', 'TRRD', 'OPTBP', 'none',...
    ... % Library option
    'Library_opt', 'full', ...
    'OPT_CRISMSPCLIB',0, 'OPT_RELAB', 0, 'OPT_CRISMTYPELIB', 0, ...
    'OPT_SPLIBUSGS', 0, 'OPT_ICELIB', [], 'OPT_SURFICELIB', [], ...
    ...
    'nIter', 2, 'Bands_Opt', 6,...
    'PRECISION', 'double', 'PROC_MODE', 'GPU_2',...
    'debug', false,...
    'lambda_update_rule', 'L1SUM',...
    'SAVE_FILE',true, 'additional_suffix', 'mcd6_1s01',...
    'save_pdir',results_path,...
    'T_UPDATE', 2, 'logT_neg', false, 'opt_bands_ignore_init', 'none', ...
    'include_ice', true);


% Make sure directory path.
TList = permute(out_bland2.T_est,[3,2,1]);
fname = ['TList_' TRRIFdata_ref.basename out_bland2.settings.suffix ...
         '.mat'];
fpath = joinPath(T_path,fname);
save(fpath,'TList');

%% Batch processing on target image
crism_obs_ref = CRISMObservation(bland_id,'SENSOR_ID','L');
TRRIFdata_ref = CRISMdata(crism_obs_ref.info.basenameIF,'');
[out_tar] = sabcondv5_pub(target_id, ...
    'FFC_MODE',false,'FFC_IF_COUNTER',1, ...'LINES',100:200,...
    'WEIGHT_MODE',1,'cal_bias_cor',0, ...
    ... Transmission options
    't_mode', 5, 'obs_id_T', TRRIFdata_ref.basename,...
    'varargin_T',{ ...
        'additional_suffix','sabcondpub_v1_mcd6_1s01', ...
        'dirpath', T_path ...
        },...
    'lambda_a',0.002,'opt_img','TRRD','OPTBP','none',...
    'nIter',2,'Bands_Opt',6, ...
    ... Library Options
    'Library_opt','full', ...
    'OPT_CRISMSPCLIB',1, 'OPT_RELAB', 1, 'OPT_CRISMTYPELIB', 4, ...
    'OPT_SPLIBUSGS',6, 'OPT_ICELIB', [], 'OPT_SURFICELIB', [], ...
    ...
    'PRECISION','double','PROC_MODE','GPU_2',...
    'debug', false, ...'DEBUG_L_PLOT',l,...
    'lambda_update_rule','L1SUM',...
    'SAVE_FILE',false,...
    'SAVE_FILE',true, 'additional_suffix', 'mcd6_1s01',...
    'save_pdir',results_path,...
    'T_UPDATE', 2, 'logT_neg', false, 'opt_bands_ignore_init', 'none', ...
    'include_ice', true);

% a means fixed for bad spectra

%% Post Processing

%%
obs_id = target_id;
obs_info = crism_get_obs_info_v2(obs_id,'download_trrif_cs',2);
csi = obs_info.central_scan_info.indx;
TRR3dataset = CRISMTRRdataset(obs_info.sgmnt_info(csi).L.trr.IF{1},'');
TRR3dataset.trr3if.load_basenamesCDR();
WAdata = TRR3dataset.trr3if.readCDR('WA'); WAdata.readimgi();
bands = crmsab_genBands_v2(WAdata.prop.wavelength_filter,6,WAdata.prop.binning,WAdata.prop.sclk);

pdir5 = results_path;
dir_sab5 = joinPath(pdir5,TRR3dataset.trr3if.dirname);
sabcond_data5_1 = SABCONDdataset(TRR3dataset.trrdif.basename,dir_sab5,...
    'suffix','sabcondpub_v1_mcd6_1s01_47A3');
%% photometric correction
DEdata = CRISMDDRdata(obs_info.sgmnt_info(csi).L.ddr.DE{1}, '');
crism_photocor_wrapper(sabcond_data5_1.nr_ds, DEdata);

%% Replace values
sabcond5_1_nr_ds_pht1 = CRISMdataCAT(...
    [sabcond_data5_1.nr_ds.basename, '_phot1'], ...
    sabcond_data5_1.nr_ds.dirpath);

crism_replace_value_wrapper(sabcond5_1_nr_ds_pht1);


end