
bland_id = '3E12';
target_id = '37AE';

%% Convolve atmospheric transmission: Testing one column at one time
crism_convolve_hitran_abscoef(bland_id,'Columns',55, ...
    'ABSCOEF_DIR', '/home/imadk/Documents/MATLAB/CRISM/crism_sabcond_main/auto_sabcond/mars_hitran', 'mcd_ver', '6_1', ...
    'h2o_scale', 1.0, 'additional_suffix', '');



%% Test the fit of the convolved ATM at one column on a bland image% First test using 
% sabcondv5_pub_column_test
%   second input is the column index
%   'debug', true        (debug mode, you can see plot of spectra and errors)
%   'DEBUG_L_PLOT',200   (line index of the spectrum shown in figures in
%                         debug mode)
% Set 'SAVE_FILE',false not to save anything.
% Make sure 
% 'varargin_T',{'additional_suffix','mean_abscoef_hitran_v7_1_1_idx0t0_ctr','dirpath','./TList'}
% is correct, especially directory path
% Library option may be important
% 'OPT_CRISMSPCLIB',0, 'OPT_RELAB', 0, 'OPT_CRISMTYPELIB',0,'OPT_SPLIBUSGS',0, ...
%     'OPT_ICELIB',6, 'OPT_SURFICELIB', 7,

crism_obs_ref = CRISMObservation(bland_id,'SENSOR_ID','L');
TRRIFdata_ref = CRISMdata(crism_obs_ref.info.basenameIF,'');
[out_t1c] = sabcondv5_pub_column_test(bland_id, 55, ...
    'FFC_MODE', false, 'FFC_IF_COUNTER', 1,...
    'WEIGHT_MODE', 1, 'cal_bias_cor', 0,...
    't_mode', 5, 'obs_id_T', TRRIFdata_ref.basename, 'varargin_T', { ...
        'additional_suffix','mean_MCDv6_1_scena1_abscoef_2020_voigt_ctr_bin0', ...
        'dirpath', '/home/imadk/data/T' ...
    },...
    'lambda_a', 0.0, 'opt_img', 'TRRD', 'OPTBP', 'none',...
    'nIter', 2, 'Bands_Opt', 6, 'Library_opt', 'full', ...
    'OPT_CRISMSPCLIB', 0, 'OPT_RELAB', 0, 'OPT_CRISMTYPELIB', 0, ...
    'OPT_SPLIBUSGS',0, 'OPT_ICELIB', [], 'OPT_SURFICELIB', [], ...
    'PRECISION', 'double', 'PROC_MODE', 'CPU_2',...
    'debug', true, 'DEBUG_L_PLOT', 175, ... 383, ...285,...
    'lambda_update_rule', 'L1SUM',...
    'SAVE_FILE', false, ...
    'T_UPDATE', 2, 'logT_neg', false, 'opt_bands_ignore_init', 'none', ...
    'include_ice', true);



%% Test on target image

crism_obs_ref = CRISMObservation(bland_id,'SENSOR_ID','L');
TRRIFdata_ref = CRISMdata(crism_obs_ref.info.basenameIF,'');
c = 607; l = 225;
c = 500; l = 200;
c=254; l = 520; % c=254; l = 200;
c = 500; l = 200;
c=602; l=175;
% c=284; l-327;
c=528; l=516;
c=100; l=100;
c=368; l=234;c=334; l=516;
c=568; l=274;c=341; l=516;
c=574;
c=55;
l=175;
[out_t1c] = sabcondv5_pub_column_test(target_id, c, ...
    'FFC_MODE',false,'FFC_IF_COUNTER',1,...'LINES',100:200,...
    'WEIGHT_MODE',1,'cal_bias_cor',0,...
    ... Transmission options
    't_mode', 5, 'obs_id_T', TRRIFdata_ref.basename,...
    'varargin_T',{ ...
        'additional_suffix' ,'sabcondpub_v1_mcd6_1s01', ...
        'dirpath', '/home/imadk/data/T' ...
        },...
    'lambda_a',0.02,'opt_img','TRRD','OPTBP','none',...
    'nIter',2,'Bands_Opt',6, ...
    ... Library Options
    'Library_opt','full', ...
    'OPT_CRISMSPCLIB',1, 'OPT_RELAB', 1, 'OPT_CRISMTYPELIB', 4, ...
    'OPT_SPLIBUSGS', 6, 'OPT_ICELIB', [], 'OPT_SURFICELIB', [], ...
    ...
    'PRECISION','double','PROC_MODE','CPU_2',...
    'debug',true,'DEBUG_L_PLOT',l,...
    'lambda_update_rule','L1SUM',...
    'SAVE_FILE',false,...
    'T_UPDATE',2,'logT_neg',false,'opt_bands_ignore_init','none', ...
    'include_ice', true);










